-- Photo Table
CREATE TABLE IF NOT EXISTS photo_db (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    entryId INTEGER NOT NULL,
    path TEXT NOT NULL,
    caption TEXT NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    fileSize INTEGER NOT NULL,
    FOREIGN KEY (entryId) REFERENCES journal_db(id) ON DELETE CASCADE
);